# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-14 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2015, 11, 14, 16, 56, 55, 916176, tzinfo=utc), max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
