# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-15 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='item',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
