# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-21 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20151115_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='item',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
